rvm:
  - 2.4.6
  - 2.5.6
  - 2.6.4
  - ruby-head

os:
  - linux
  - osx
osx_image: xcode11.2

dist: trusty

gemfile:
  - Gemfile

before_install:
  - gem update --system=2.7.8

script: bundle exec rake test

matrix:
  allow_failures:
    - rvm: ruby-head
